#!/bin/sh
# ssh -aliases
alias sshpi="ssh finn@192.168.0.17"
# alias sshdesktop="ssh -p 5522 finn@finnsev.ddns.net"
alias sshdesktop="ssh -p 5522 finn@192.168.0.64"
alias unlock_pacman="rm -rf /var/lib/pacman/db.lck"
# make doas work with zsh aliases
alias doas='doas '


# get fastest mirrors
alias mirror="doas reflector -p "https" -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="doas reflector -p "https" --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="doas reflector -p "https" --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="doas reflector -p "https" --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Colorize ls
alias ls='ls --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# For when keys break
alias archlinux-fix-keys="doas pacman-key --init && doas pacman-key --populate archlinux && doas pacman-key --refresh-keys"

# Use neovim instead of vim

# alias vim='nvim'
alias vim='nvim'

# make background of asciiquarium transparent
alias asciiquarium="asciiquarium -t"

# alias for fast navigation
alias conf="cd ~/.config"
alias haw="cd ~/Dokumente/Hochschule/Master/2_Semester"
alias master="cd ~/Dokumente/Hochschule/Master/3_Semester/Masterarbeit/"
