#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.matlab_install/bin/":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/bin/lvim:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
export CPATH=$CPATH:/usr/include/opencv4 # Add OPENCV to Path
export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# Default Apps
export EDITOR='lvim'
export READER='zathura'
export VISUAL='lvim'
export TERMINAL='alacritty'
export BROWSER='firefox'
export VIDEO='mpv'
export IMAGE='sxiv'


export PATH=$PATH:/home/finn/.spicetify
